baseURL = "https://eclipse.dev/kanto/"
title = "Eclipse Kanto™ | IoT edge software stack"

enableRobotsTXT = true

# disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "autumn"

# Configure how URLs look like per section.
[permalinks]
# blog = "/ = section/ = year/ = filename/"

## Configuration for BlackFriday markdown parser =  https://github.com/russross/blackfriday
## [blackfriday]
## plainIDAnchors = true
## hrefTargetBlank = true
## angledQuotes = false
## latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "Smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
      style = "autumn"
      # Uncomment if you want your chosen highlight style used for code blocks without a specified language
      # guessSyntax = "true"
  [markup.tableOfContents]
      endLevel = 6
      startLevel = 1

# Everything below this are Site Params

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
section = ["HTML", "print"]

[params]
copyright = "The Eclipse Kanto™ Project"
# privacy_policy = "https://eclipse.org/legal/privacy.php"

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the
# current doc set.
# version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
# url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/eclipse-kanto/kanto"
github_subdir = "site"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/eclipse-kanto"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Uncomment this if you have a newer GitHub repo with "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
# github_branch= "dev"

# Enable Lunr.js offline search
offlineSearch = true
offlineSearchMaxResults = 50

# Enable Algolia DocSearch
params.search.algolia = false

# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting = true

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
ul_show = 2
# Uncomment to enable foldable menu.
sidebar_menu_foldable = true
# Uncomment to disable breadcrumb navigation.
# breadcrumb_disable = true
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = true
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true
# Max amount of entries on the side bar
sidebar_menu_truncate = 80

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
    name = "Eclipse Kanto project"
    url = "https://projects.eclipse.org/projects/iot.kanto"
    icon = "fas fa-external-link-alt"
    desc = "Welcome to our Eclipse IoT home"
[[params.links.user]]
  name = "Stack Overflow"
  url = "https://stackoverflow.com/questions/tagged/eclipse-kanto"
  icon = "fab fa-stack-overflow"
  desc = "Ask practical questions for eclipse-kanto"
[[params.links.user]]
    name = "YouTube"
    url = "https://www.youtube.com/watch?v=bMN_ZiUS3Bc"
    icon = "fab fa-youtube"
    desc = "From \"Can't\" to \"Can\" with Kanto"
[[params.links.user]]
    name = "Newsletter"
    url = "https://newsroom.eclipse.org/eclipse-newsletter/2022/february/five-ways-eclipse-kanto-accelerates-iot-edge-development"
    icon = "fas fa-book-open"
    desc = "Five Ways Eclipse Kanto Accelerates IoT Edge Development"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
    name = "GitHub"
    url = "https://github.com/eclipse-kanto"
    icon = "fab fa-github"
    desc = "Development takes place here!"
[[params.links.developer]]
    name = "Releases"
    url = "https://github.com/eclipse-kanto/kanto/releases"
    icon = "fas fa-rocket"
    desc = "Try out the latest release!"
[[params.links.developer]]
    name = "Task board"
    url = "https://github.com/orgs/eclipse-kanto/projects/1/views/1"
    icon = "fas fa-clipboard-list"
    desc = "Check out the roadmap and ongoing work"
[[params.links.developer]]
    name = "Developer mailing list"
    url = "https://accounts.eclipse.org/mailing-list/kanto-dev"
    icon = "fa fa-envelope"
    desc = "Join developer discussions"

# Eclipse relevant links. These will show up at the bottom footer line.
[[params.links.eclipse]]
  url = "https://eclipse.org"
  name = "Eclipse Foundation"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/privacy.php"
  name = "Privacy Policy"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/termsofuse.php"
  name = "Terms of Use"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/copyright.php"
  name = "Copyright Agent"

[[params.links.eclipse]]
  url = "https://eclipse.org/legal/"
  name = "Legal"

[[params.links.eclipse]]
  url = "https://github.com/eclipse-kanto/kanto/raw/main/LICENSE"
  name = "License"

[[params.links.eclipse]]
  url = "https://eclipse.org/security/"
  name = "Report a Vulnerability"

[taxonomies]
tag = "tags"
category = "categories"
year = "year"

[module]
  proxy = "direct"
  [module.hugoVersion]
    extended = true
    min = "0.110.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

  # [[module.mounts]]
  #     # The following entry is the one we actually need, to be able to
  #     # refer to it in our own assets/scss files.
  #     source = "assets/scss"
  #     target = "assets/scss/docsy"
  #     # Unfortunately that means we need to redefine all of Docsy's
  #     # module mounts here...
  #     # https://github.com/google/docsy/commit/215f68033bbc7bddf8dbec2bbabf8749d1998a17 (lines 24f)
  #     #
  #     # I hope this use-case will be simplified one day.
  # [[module.mounts]]
  #     source = "content"
  #     target = "content"
  # [[module.mounts]]
  #     source = "static"
  #     target = "static"
  # [[module.mounts]]
  #     source = "layouts"
  #     target = "layouts"
  # [[module.mounts]]
  #     source = "data"
  #     target = "data"
  # [[module.mounts]]
  #     source = "assets"
  #     target = "assets"
  # [[module.mounts]]
  #     source = "i18n"
  #     target = "i18n"
  # [[module.mounts]]
  #     source = "archetypes"
  #     target = "archetypes"
  # [[module.mounts]]
  #     source = "node_modules/bootstrap"
  #     target = "assets/vendor/bootstrap"
  # [[module.mounts]]
  #     source = "node_modules/@fortawesome/fontawesome-free"
  #     target = "assets/vendor/Font-Awesome"
  # [[module.mounts]]
  #     source = "node_modules/@fortawesome/fontawesome-free/webfonts"
  #     target = "static/webfonts"