name: Release

on:
  push:
    tags:
      - 'v*'
env:
  BUILD_TMP: ./build-tmp

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kanto
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout suite-connector
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/suite-connector
          path: ${{ env.BUILD_TMP }}/suite-connector
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout container-management
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/container-management
          path: ${{ env.BUILD_TMP }}/container-management
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout file-upload
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/file-upload
          path: ${{ env.BUILD_TMP }}/file-upload
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout software-update
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/software-update
          path: ${{ env.BUILD_TMP }}/software-update
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout local-digital-twins
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/local-digital-twins
          path: ${{ env.BUILD_TMP }}/local-digital-twins
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout suite-bootstrapping
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/suite-bootstrapping
          path: ${{ env.BUILD_TMP }}/suite-bootstrapping
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout file-backup
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/file-backup
          path: ${{ env.BUILD_TMP }}/file-backup
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Checkout system-metrics
        uses: actions/checkout@v2
        with:
          repository: eclipse-kanto/system-metrics
          path: ${{ env.BUILD_TMP }}/system-metrics
          ref: ${{ github.ref }}
          token: ${{ secrets.WF_AUTH }}
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: ~> 1.5
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # GOPATH is no longer exported by the actions/setup-go@v2
          # https://github.com/actions/setup-go/issues/12#issuecomment-604605595
          # https://github.com/goreleaser/goreleaser-action/issues/267
          GOPATH: /home/runner/go
