[build]
publish = "site/public"
command = "chmod +x build-site.sh && ./build-site.sh"

[build.environment]
GO_VERSION = "1.21.4"

[context.production.environment]
HUGO_VERSION = "0.122.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "chmod +x build-site.sh && ./build-site.sh"

[context.deploy-preview.environment]
HUGO_VERSION = "0.122.0"

[context.branch-deploy]
command = "chmod +x build-site.sh && ./build-site.sh"

[context.branch-deploy.environment]
HUGO_VERSION = "0.122.0"